dataset:
  - type: dali-folder
    args:
      features: [win, valid, minimaps, scalars]
      load_other_player: True
    val_loader:
      type: DALI
      args:
        batch_size: 64
        drop_last: true
    train_loader:
      type: DALI
      args:
        shuffle: true
        batch_size: 64
        drop_last: true
criterion:
  - type: win-bce
    args: {}
model:
  - type: snapshot-prediction
    args:
      dropout: 0.2
      image_enc:
        type: image-v1
        args:
          in_ch: 12
      scalar_enc:
        type: scalar-v2
        args:
          strategy: batch_norm
          use_other_player: True
      decoder:
        type: scalar-v1
        args:
          out_ch: 1
    optimizer:
      type: adam
      args:
        step_interval: 1
        lr: 1.e-5
        gradient_clipping: 0.01
      scheduler:
        type: poly
        args:
          max_iter: 25
          power: 0.9
logger:
  interval: 500
